//! Seatbelt sandbox implementation for macOS
//!
//! Uses Apple's sandbox_exec (Seatbelt) for macOS sandboxing.

use crate::{SandboxCapabilities, SandboxConfig, SandboxProvider};
use sigil_core::{ResolvedCommand, Result, SigilError};
use std::process::Command;

/// Default tmpfs mount point for secret file injection on macOS
const SECRET_TMPFS_MACOS: &str = "/tmp/sigil-secrets";

/// Seatbelt sandbox implementation for macOS
///
/// Uses Apple's sandbox-exec with dynamically generated Scheme-based profiles.
pub struct SeatbeltSandbox {
    /// Path to the sandbox-exec binary
    sandbox_exec_path: std::path::PathBuf,
}

impl SeatbeltSandbox {
    /// Create a new Seatbelt sandbox
    pub fn new() -> Result<Self> {
        Ok(Self {
            sandbox_exec_path: std::path::PathBuf::from("sandbox-exec"),
        })
    }

    /// Create a Seatbelt sandbox with a custom sandbox-exec path
    pub fn with_sandbox_exec_path<P: AsRef<std::path::Path>>(path: P) -> Self {
        Self {
            sandbox_exec_path: path.as_ref().to_path_buf(),
        }
    }

    /// Check if sandbox-exec is available on the system
    fn check_sandbox_exec_available(&self) -> bool {
        // Try to run sandbox-exec with a simple test
        std::process::Command::new(&self.sandbox_exec_path)
            .arg("-p")
            .arg("(version 1)")
            .arg("true")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    }

    /// Generate a Seatbelt profile from the sandbox configuration
    fn generate_profile(&self, config: &SandboxConfig) -> String {
        let mut profile =
            String::from(";; Generated by SIGIL — do not edit\n(version 1)\n(deny default)\n\n");

        // Read-only filesystem access
        profile.push_str(";; Read-only filesystem access\n");
        profile.push_str("(allow file-read* (subpath \"/usr\") (subpath \"/bin\") (subpath \"/Library\") (subpath \"/System\"))\n\n");

        // Project directory writable
        if let Some(project_dir) = &config.project_dir {
            profile.push_str(&format!(
                ";; Project directory writable\n\
                 (allow file-write* (subpath \"{}\"))\n\n",
                project_dir.display()
            ));
        }

        // Tmpfs for secret injection
        profile.push_str(&format!(
            ";; Secret injection tmpfs\n\
             (allow file-write* (subpath \"{}\"))\n\n",
            SECRET_TMPFS_MACOS
        ));

        // Network blocking
        if config.network_isolated {
            profile.push_str(";; Block network\n(deny network*)\n\n");
        }

        // Block process inspection
        profile.push_str(";; Block process inspection\n(deny process-info*)\n\n");

        // Allow execution
        profile.push_str(";; Allow execution\n(allow process-exec (subpath \"/usr/bin\") (subpath \"/bin\") (subpath \"/usr/local/bin\"))\n");

        profile
    }

    /// Build the sandbox command with Seatbelt profile
    fn build_sandbox_command(
        &self,
        resolved_cmd: &ResolvedCommand,
        config: &SandboxConfig,
    ) -> Result<Command> {
        let mut cmd = Command::new(&self.sandbox_exec_path);

        // Generate the Seatbelt profile
        let profile = self.generate_profile(config);

        // Add the profile argument
        cmd.arg("-f").arg("-").arg(profile);

        // Set environment variables
        for (name, value) in &config.env_vars {
            cmd.env(name, value);
        }

        // Block dangerous environment variables
        cmd.env_remove("LD_PRELOAD");
        cmd.env_remove("LD_LIBRARY_PATH");
        cmd.env_remove("DYLD_INSERT_LIBRARIES");
        cmd.env_remove("DYLD_LIBRARY_PATH");

        // Set working directory if specified
        if let Some(wd) = &config.working_dir {
            cmd.current_dir(wd);
        }

        // Add the command to execute
        let parts = shell_words::split(&resolved_cmd.resolved)
            .map_err(|e| SigilError::InvalidConfig(format!("Invalid command: {}", e)))?;

        if parts.is_empty() {
            return Err(SigilError::InvalidConfig("Empty command".to_string()));
        }

        cmd.arg(&parts[0]);
        for arg in &parts[1..] {
            cmd.arg(arg);
        }

        Ok(cmd)
    }

    /// Apply PT_DENY_ATTACH to prevent debugger attachment
    ///
    /// This is the macOS equivalent of Linux's PR_SET_DUMPABLE=0.
    /// Note: This requires unsafe code and ptrace functionality.
    #[cfg(target_os = "macos")]
    pub fn apply_ptrace_deny_attach() -> Result<()> {
        // PT_DENY_ATTACH prevents debuggers from attaching to the process
        // This is a macOS-specific syscall
        const PT_DENY_ATTACH: u32 = 31;

        unsafe {
            // Use libc's ptrace function
            let ret = libc::ptrace(
                PT_DENY_ATTACH as i32,
                0,
                std::ptr::null_mut::<libc::c_void>(),
                0,
            );

            if ret != 0 {
                return Err(SigilError::Backend(format!(
                    "Failed to apply PT_DENY_ATTACH: {}",
                    std::io::Error::last_os_error()
                )));
            }
        }

        Ok(())
    }

    /// Apply PT_DENY_ATTACH to prevent debugger attachment
    ///
    /// This is a no-op on non-macOS platforms.
    #[cfg(not(target_os = "macos"))]
    pub fn apply_ptrace_deny_attach() -> Result<()> {
        Err(SigilError::Backend(
            "PT_DENY_ATTACH is only available on macOS".to_string(),
        ))
    }
}

impl Default for SeatbeltSandbox {
    fn default() -> Self {
        Self::new().unwrap()
    }
}

impl SandboxProvider for SeatbeltSandbox {
    fn wrap_command(&self, cmd: &ResolvedCommand, config: &SandboxConfig) -> Result<Command> {
        self.build_sandbox_command(cmd, config)
    }

    fn provider_name(&self) -> &str {
        "seatbelt"
    }

    fn is_available(&self) -> bool {
        self.check_sandbox_exec_available()
    }

    fn capabilities(&self) -> SandboxCapabilities {
        SandboxCapabilities {
            network_namespace: false, // Seatbelt doesn't use network namespaces
            pid_namespace: false,     // Seatbelt doesn't use PID namespaces
            mount_namespace: false,   // Seatbelt doesn't use mount namespaces
            seccomp: false,           // Seatbelt uses its own filtering
            file_injection: true,
            bind_mounts: false, // Seatbelt doesn't support bind mounts
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_seatbelt_sandbox_creation() {
        let sandbox = SeatbeltSandbox::new();
        assert!(sandbox.is_ok());
    }

    #[test]
    fn test_seatbelt_sandbox_provider_name() {
        let sandbox = SeatbeltSandbox::new().unwrap();
        assert_eq!(sandbox.provider_name(), "seatbelt");
    }

    #[test]
    fn test_seatbelt_sandbox_default() {
        let sandbox = SeatbeltSandbox::default();
        assert_eq!(sandbox.provider_name(), "seatbelt");
    }

    #[test]
    fn test_seatbelt_sandbox_capabilities() {
        let sandbox = SeatbeltSandbox::new().unwrap();
        let caps = sandbox.capabilities();
        assert!(!caps.network_namespace);
        assert!(!caps.pid_namespace);
        assert!(!caps.mount_namespace);
        assert!(!caps.seccomp);
        assert!(caps.file_injection);
        assert!(!caps.bind_mounts);
    }

    #[test]
    fn test_seatbelt_sandbox_generate_profile() {
        let sandbox = SeatbeltSandbox::new().unwrap();
        let config = SandboxConfig::default();

        let profile = sandbox.generate_profile(&config);
        assert!(profile.contains("(version 1)"));
        assert!(profile.contains("(deny default)"));
        assert!(profile.contains("(allow file-read*"));
        assert!(profile.contains("(deny network*)"));
        assert!(profile.contains("(deny process-info*)"));
    }

    #[test]
    fn test_seatbelt_sandbox_generate_profile_with_project_dir() {
        let sandbox = SeatbeltSandbox::new().unwrap();
        let config = SandboxConfig::with_project_dir(std::path::PathBuf::from("/test/project"));

        let profile = sandbox.generate_profile(&config);
        assert!(profile.contains("/test/project"));
        assert!(profile.contains("(allow file-write*"));
    }

    #[test]
    fn test_seatbelt_sandbox_generate_profile_with_network() {
        let sandbox = SeatbeltSandbox::new().unwrap();
        let config = SandboxConfig::default().with_network_isolation(true);

        let profile = sandbox.generate_profile(&config);
        assert!(profile.contains("(deny network*)"));
    }

    #[test]
    fn test_seatbelt_sandbox_generate_profile_without_network() {
        let sandbox = SeatbeltSandbox::new().unwrap();
        let config = SandboxConfig::default().with_network_isolation(false);

        let _profile = sandbox.generate_profile(&config);
        // Profile should not contain network denial when not isolated
        // (though it might still deny by default with (deny default))
    }
}
