/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * SIGIL SDK client for Node.js
 *
 * This client connects to the SIGIL daemon via Unix socket and provides
 * methods for interacting with secrets.
 */
export declare class SigilClient {
  /** Create a new SIGIL client with default socket path */
  constructor()
  /** Connect to the SIGIL daemon (verifies connection) */
  connect(): Promise<void>
  /** Get a secret value by path */
  get(path: string): Promise<string>
  /** Resolve placeholders in a string */
  resolve(input: string): Promise<string>
  /** Check if a secret exists */
  exists(path: string): Promise<boolean>
  /** List secrets with a given prefix */
  list(prefix: string): Promise<Array<SecretMetadata>>
}

/** Secret metadata for Node.js */
export interface SecretMetadata {
  /** Secret path */
  path: string
  /** Secret type */
  secretType: string
  /** Creation timestamp (RFC3339) */
  createdAt: string
  /** Last update timestamp (RFC3339) */
  updatedAt: string
  /** Tags */
  tags: Array<string>
  /** Notes */
  notes?: string
}
