/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * SIGIL SDK client for Node.js
 *
 * This client connects to the SIGIL daemon via Unix socket and provides
 * methods for interacting with secrets.
 */
export declare class SigilClient {
  /** Create a new SIGIL client with default socket path */
  constructor()
  /**
   * Create a new SIGIL client with a custom socket path
   *
   * @param socketPath - Path to the SIGIL daemon Unix socket
   */
  static withSocketPath(socketPath: string): SigilClient
  /**
   * Create a new SIGIL client and load session token from file
   *
   * This attempts to read the session token from the standard location
   * ($XDG_RUNTIME_DIR/sigil-session-token) and configure the client with it.
   */
  static withToken(): SigilClient
  /** Connect to the SIGIL daemon (verifies connection) */
  connect(): Promise<void>
  /**
   * Get a secret value by path
   *
   * @param path - Secret path (e.g., "kalshi/api_key")
   */
  get(path: string): Promise<string>
  /**
   * Resolve placeholders in a string
   *
   * @param input - String containing placeholders like `{{secret:path}}`
   */
  resolve(input: string): Promise<string>
  /**
   * Check if a secret exists
   *
   * @param path - Secret path to check
   */
  exists(path: string): Promise<boolean>
  /**
   * List secrets with a given prefix
   *
   * @param prefix - Optional prefix to filter secrets (e.g., "aws/")
   */
  list(prefix: string): Promise<Array<SecretMetadata>>
  /**
   * Request access to a secret (triggers TUI approval workflow)
   *
   * @param path - Secret path to request access for
   * @param reason - Reason for the access request
   * @param durationSecs - Optional duration in seconds for time-bounded access
   */
  requestAccess(path: string, reason: string, durationSecs?: number | null): Promise<AccessGrant>
  /**
   * Scrub secrets from output
   *
   * @param output - Output string that may contain secrets
   */
  scrub(output: string): Promise<string>
  /** Get daemon status information */
  status(): Promise<DaemonStatusInfo>
  /**
   * Execute a command with automatic secret injection and output scrubbing
   *
   * @param command - Command to execute (e.g., "aws")
   * @param args - Command arguments
   * @param workingDir - Optional working directory
   * @param networkIsolated - Whether to enable network isolation
   * @param projectDir - Optional project directory for signature lookup
   * @param timeoutSecs - Timeout in seconds (0 = no timeout)
   */
  exec(
    command: string,
    args: Array<string>,
    workingDir: string | null,
    networkIsolated: boolean,
    projectDir: string | null,
    timeoutSecs: number
  ): Promise<ExecResult>
  /**
   * List available sealed operations
   *
   * Returns a list of operations that can be executed with approval.
   */
  listOperations(): Promise<Array<OperationDescription>>
}

/** Secret metadata for Node.js */
export interface SecretMetadata {
  /** Secret path */
  path: string
  /** Secret type */
  secretType: string
  /** Creation timestamp (RFC3339) */
  createdAt: string
  /** Last update timestamp (RFC3339) */
  updatedAt: string
  /** Tags */
  tags: Array<string>
  /** Notes */
  notes?: string | null
}

/** Result of an access request */
export interface AccessGrant {
  /** Whether access was granted */
  granted: boolean
  /** When the grant expires (if applicable) */
  expiresAt?: string | null
}

/** Daemon status information */
export interface DaemonStatusInfo {
  /** Whether the daemon is running */
  running: boolean
  /** Daemon uptime in seconds */
  uptimeSecs: number
  /** Number of active sessions */
  activeSessions: number
  /** Number of secrets loaded */
  secretsLoaded: number
}

/** Result of executing a command */
export interface ExecResult {
  /** Command exit code */
  exitCode: number
  /** Command stdout (scrubbed) */
  stdout: string
  /** Command stderr (scrubbed) */
  stderr: string
  /** Whether the command timed out */
  timedOut: boolean
  /** Execution duration in milliseconds */
  durationMs: number
  /** Number of secrets detected and scrubbed from output */
  secretsScrubbed: number
  /** Signatures that matched for auto-injection */
  matchedSignatures: Array<string>
}

/** Description of a sealed operation */
export interface OperationDescription {
  /** Operation ID */
  id: string
  /** Human-readable description */
  description: string
  /** Whether this operation requires approval */
  requiresApproval: boolean
}
